org: naheller
app: price-tracker
service: price-tracker
frameworkVersion: "3"

custom:
  tableNameProducts: "products"
  # dynamodb:
  # stages:
  #   - dev
  # start:
  #   port: 8000
  #   migrate: true
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
      # docker: false
      # noStart: true

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ProductsTable, Arn]
  environment:
    PRODUCTS_TABLE: ${self:custom.tableNameProducts}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNameProducts}

plugins:
  - serverless-dynamodb
  - serverless-offline
